In [2]:
import numpy as np

In [16]:
list_1 = [10,20,30,40,50,60]
print(f"List  - {list_1}")

array_1 = np.array(list_1)
print(f"Array - {array_1}")

List  - [10, 20, 30, 40, 50, 60]
Array - [10 20 30 40 50 60]


In [15]:
array_2 = np.append(array_1,70)
print(f"Append method 1 : {array_2}")

array_2 = np.append(array_2,[80])
print(f"Append method 2 : {array_2}")

Append method 1 : [10 20 30 40 50 60 70]
Append method 2 : [10 20 30 40 50 60 70 80]


In [17]:
#Vectorized Operations

arr = np.array([10,20,30,40,50,60])

arr = arr + 1
print(f"Adding         : {arr}")

arr = arr - 1
print(f"Subtracting    : {arr}")

arr = arr * 5
print(f"Multiplying    : {arr}")

arr = arr // 2
print(f"Floor Dividing : {arr}")

arr = arr / 2
print(f"Dividing       : {arr}")

Adding         : [11 21 31 41 51 61]
Subtracting    : [10 20 30 40 50 60]
Multiplying    : [ 50 100 150 200 250 300]
Floor Dividing : [ 25  50  75 100 125 150]
Dividing       : [12.5 25.  37.5 50.  62.5 75. ]


In [34]:
arr = np.array([70,30,90,40,50,10])
min = arr[0]
max = arr[0]
for i in arr:
    if i < min:
        min = i
    if i > max:
        max = i

print("Minimum",min)
print("Maximum",max)

Minimum 10
Maximum 90


In [ ]:
arr1 = np.array([70,30,90,40,50,10])

In [7]:
arr1 = np.array([1, 2, 3])  # 1D array
arr2 = np.array([[1, 2], [3, 4]])  # 2D array
print(arr1)
print(arr2)

[1 2 3]
[[1 2]
 [3 4]]


In [12]:
print("3x3 array of zeros")
print(np.zeros((3, 3)))
print()

print("2x4 array of ones")
print(np.ones((2, 4)))
print()

print("Identity matrix")
print(np.eye(3))
print()

print("2x2 array filled with 7")
print(np.full((2, 2), 7))
print()

print("Array from 0 to 10 with step 2")
print(np.arange(0, 10, 2))
print()

print("5 equally spaced numbers between 0 and 1")
print(np.linspace(0, 1, 5))

3x3 array of zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

2x4 array of ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

2x2 array filled with 7
[[7 7]
 [7 7]]

Array from 0 to 10 with step 2
[0 2 4 6 8]

5 equally spaced numbers between 0 and 1
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[::2])

[20 30 40]
[10 30 50]


In [ ]:
#2D Slicing
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0, 1])
print(arr2[:, 1])

2
[2 5]


In [16]:
#Broadcasting
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
print(arr1 + arr2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [18]:
#Aggragated Functions
arr = np.array([70,30,90,40,50,10])

print(arr.sum())        # Sum of elements
print(arr.mean())       # Mean
print(arr.min())
print(arr.max())  # Minimum, maximum
print(arr.std())        # Standard deviation
print(arr.argmin())     # Index of the minimum value
print(arr.argmax())     # Index of the maximum value


290
48.333333333333336
10
90
26.087459737497547
5
2


In [ ]:
#Sort with Built-In Function

arr = np.array([70,30,90,40,50,10])

arr.sort()
print("Ascending Sort ",arr)

arrdesc = np.sort(arr)[::-1]
print("Descending Sort",arrdesc)

Ascending Sort  [10 30 40 50 70 90]
Descending Sort [90 70 50 40 30 10]


In [23]:
arr = np.array([3, 1, 4, 1, 5])
desc_sorted = np.sort(arr)[::-1]
print("Descending:", desc_sorted)


Descending: [5 4 3 1 1]


In [21]:
arr = np.array([[3, 2, 1], [6, 5, 4]])

# Sort along rows (default axis=-1)
sorted_rows = np.sort(arr, axis=1)
print("Rows sorted:", sorted_rows)

# Sort along columns (axis=0)
sorted_columns = np.sort(arr, axis=0)
print("Columns sorted:", sorted_columns)

Rows sorted: [[1 2 3]
 [4 5 6]]
Columns sorted: [[3 2 1]
 [6 5 4]]
